### ISSUE TITLE
Couldn't find a table (install Rtools)

### ISSUE THREAD

**Issue by tianyiwangnova** [crubba/htmltab#22]
Hey I was trying to install rtools and I got this error:
```r
> install.Rtools()
Loading required package: htmltab
also installing the dependency ‘XML’

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/XML_3.99-0.3.zip'
Content type 'application/zip' length 4258278 bytes (4.1 MB)
downloaded 4.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/htmltab_0.7.1.1.zip'
Content type 'application/zip' length 100112 bytes (97 KB)
downloaded 97 KB

package ‘XML’ successfully unpacked and MD5 sums checked
package ‘htmltab’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\tiawan\AppData\Local\Temp\RtmpYtPR8J\downloaded_packages
Loading required package: htmltab
If you find a bug, please report it to 'https://github.com/crubba/htmltab/issues'
Use suppressPackageStartupMessages to eliminate package startup messages.
No encoding supplied: defaulting to UTF-8.
Argument 'which' was left unspecified. Choosing first table.
Error: Couldn't find a table.
```

Can you help me have a look? Thanks!

**Comment by burgerga** [comment]
Is not an issue in htmltab but in installr (https://github.com/talgalili/installr/issues/148). I am working on a solution. You can close this issue.

**Comment by burgerga** [comment]
It has since been fixed in installer 

EDIT: CRAN might not be up-to-date yet; install the github version with `remotes::install_github("talgalili/installr")`

**Comment by rstraete** [comment]
Hi Gerhard.

Today I installed R version 4.0.4 in Rstudio version  1.1.419 on windows 10 Enterprise version 1809 on a 64-bit operating system.

I installed "installr" package, "devtools" package and "htmlab" package.

The version of package installr is 0.22.0.

I still received the same error:

> install.Rtools()
Loading required package: htmltab
No encoding supplied: defaulting to UTF-8.
Argument 'which' was left unspecified. Choosing first table.
Error: Couldn't find a table.

Any suggestion on what I'm doing wrong?

Thx,
Roel
